[DATABASE]
DB_USER = username
DB_PASS = password
DB_HOST = localhost
DB_NAME = filemanager

[REDIS]
REDIS_ENABLED = True
REDIS_HOST = localhost
REDIS_PORT = 6379

[SYSTEM]
SECRET_KEY = 00ccc30a9367c4431f5475a5817c826fd35c61cf738d0341
DEBUG = False
